---
- name: Configure NoAutoplayfornonVolume
  hosts: windows
  tasks:
    - name: Set NoAutoplayfornonVolume registry key
      ansible.windows.win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windows\Explorer
        name: NoAutoplayfornonVolume
        data: 1
        type: dword
