---
- name: Promt for Password
  hosts: windows
  tasks:
    - name: Windows Remote Desktop Configured to Always Prompt for Password
      ansible.windows.win_regedit:
        key: HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services
        value: fPromptForPassword
        datatype: dword
        data: 1